/**
*	Filename: sprite.h
*
*	Description: Main header for Sprite Component, Texture has to be generated by the renderer
*
*	Version: 1/11/2018
*
*	© 2018, Jens Heukers
*/


#pragma once
#include "component.h"
#include "../math/vector2.h"
#include "../resourcemanager.h"
#include "../texture.h"
#include "../core.h"

class Sprite : public Component {
private:
	/// @brief the path to the texture (in system)
	const char* texturePath;

	/// @brief the texture pointer
	Texture* texture;
public:
	/**
	* Default Constructor
	*/
	Sprite() { this->typeName = typeid(*this).name(); this->texture = nullptr; };

	/**
	* Returns the surface if found, returns nullptr if failed
	*/
	Texture* GetTexture();
	
	/**
	* Creates a new surface, by loading image bmp file
	*/
	void SetTexture(std::string path);

	const char* GetSurfacePath();

	Component* Copy();
	void OnLoad(const char* data);
};