/**
*	Filename: sprite.h
*
*	Description: Main header for Sprite Component, Texture has to be generated by the renderer
*
*	© 2018, Jens Heukers
*/


#pragma once
#include "component.h"
#include "../math/vector2.h"
#include "../resourcemanager.h"
#include "../texture.h"
#include "../core.h"
#include <GL/GL.h>

class Sprite : public Component {
private:
	const char* texturePath;
	Texture* texture;
	GLuint convertedTexture;
public:
	/**
	* Default Constructor
	*/
	Sprite() { this->typeName = typeid(*this).name(); this->texture = nullptr; };

	/**
	* Returns the surface if found, returns nullptr if failed
	*/
	Texture* GetTexture();
	
	/**
	* Creates a new surface, by loading image bmp file
	*/
	void SetTexture(const char* path);

	const char* GetSurfacePath();

	/**
	* Generates the texture 
	*/
	void GenerateConvertedTexture();

	/**
	* Returns the texture if generated
	*/
	GLuint GetConvertedTexture();

	Component* Copy();
	void OnLoad(const char* data);
};